application:
  resource-url: http://localhost:8763/api/v1/files
  user-default-thumbnail-name: default_user_thumbnail.jpg

server:
  port: 8766

spring:
  application:
    name: file-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    enabled: true
