server:
  port: 8765

spring:
  application:
    name: exam-service
  datasource:
    url: jdbc:postgresql://localhost:5432/online-exam-db-1
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    enabled: true

app:
  format:
    date: yyyy-MM-dd HH:mm:ss.ffffff
  url:
    check-upload-exam-endpoint: http://localhost:8764/
    upload-img-endpoint: http://localhost:8766/api/v1/files
    update-img-endpoint: http://localhost:8766/api/v1/files/image/updateImage
  i18n:
    baseName: messages
    defaultLocale: en
  file:
    pdf-settings:
      content:
        footer-text-vn: Bài thi được tải xuống từ do-online-exam
        footer-text-en: The exam is downloaded from do-online-exam
      position:
        max-width-row: 590
        spacing-each-question: 0
        spacing-each-answer: 0
      color:
        title-color: 0,0,0
        footer-color: 0,0,0
      font:
        font-style-normal: font/Arial Unicode MS.ttf
        font-style-bold: font/ARIALBD.TTF
        font-style-bold-italic: font/ARIALBI 1.TTF
        fz-footer: 10
        fz-question: 12
        fz-page-number: 11
  mail:
    hostname: smtp.gmail.com
    sslport: 465
    email: nqa25041998@gmail.com
    password: guitataewidxwcap