server:
  servlet:
    context-path: /
  port: 8765

#spring config
spring:
  application:
    name: exam-service
  datasource:
    url: jdbc:postgresql://localhost:5432/online-exam-db-2
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
#openapi config
openapi:
  service:
    title: exam-service doc
    version: 1.0.0
    url: http://localhost:8763
springdoc:
  api-docs:
    path: /api/v1/exams/v3/api-docs
  swagger-ui:
    path: /api/v1/exams/swagger-ui.html
#eureka config
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    enabled: true

app:
  format:
    date: yyyy-MM-dd HH:mm:ss
  url:
    check-upload-exam-endpoint: http://localhost:8764/api/v1/auth/check/user-actions
    create-accounts-exam-endpoint: http://localhost:8764/api/v1/auth/accounts-exam/registerAccountExam
    upload-img-endpoint: http://localhost:8766/api/v1/files
    update-img-endpoint: http://localhost:8766/api/v1/files/image/updateImage
  i18n:
    baseName: messages
    defaultLocale: en
  mail:
    hostname: smtp.gmail.com
    sslport: 465
    email: nqa25041998@gmail.com
    password: guitataewidxwcap
