server:
  port: 8768

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/online-exam-db-2
    username: root
    password: 123456123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  rabbitmq:
    addresses: localhost:5672
#rabbitmq config
app:
  format:
    date: yyyy-MM-dd HH:mm:ss
  rabbitmq:
    exchanges:
      internal:
        notify-exchange: internal.notify.exchange
        topic-exchange: internal.topic.exchange
    queues:
      notification-queue: notification.queue
      topic-queue: topic.queue
    routing-keys:
      internal-topic: internal.topic.routing-key
      internal-notification: internal.notification.routing-key
  firebase:
    firebase-configuration-file: j-do-exam-online-fcm-firebase-adminsdk-m701j-5bb4848d99.json
  i18n:
    baseName: messages
    defaultLocale: en
#eureka config
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    enabled: true
