#server port
server:
  port: 8400

#config for rabbit-mq
spring:
  application:
    name: test-service

#config for eureka client connect to eureka server
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    enabled: true
