#server port
server:
  port: 8764

#config for rabbit-mq
spring:
  application:
    name: authorization-service
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  #    listener:
  #      simple:
  #        max-concurrency: 10
  #        default-requeue-rejected: false
  #        auto-startup: true
  #        idle-event-interval: 5000
  #        shutdown-timeout: 10000
  #        acknowledge-mode: manual
  #        prefetch: 10
  #config connect DB
  datasource:
    url: jdbc:postgresql://localhost:5432/online-exam-db-1
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '228866512057-eunout12b3hr962mcmeuspl7cfjlnvh3.apps.googleusercontent.com'
            client-secret: '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'

            scope:
              - email
              - profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: nqa25041998@gmail.com
    password: guitataewidxwcap
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#config for eureka client connect to eureka server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    enabled: true

app:
  format:
    date: yyyy-MM-dd HH:mm:ss.ffffff
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expiration: 1000
  i18n:
    baseName: messages
    defaultLocale: en
  default-user-thumbnail: http://localhost:8763/api/v1/files/images/users/default_user_thumbnail.jpg
  file-service-endpoint: http://localhost:8103/api/v1/files/image/updateImage
  upload-rule:
    user: 5
    user-premium: 0
