#server port
server:
  port: 8761

#server name
spring:
  application.name: eureka-server

#config eureka client to connect eureka server but fetchRegistry false
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    enabled: true
