server:
  servlet:
    context-path: /
  port: 8769

#spring config
spring:
  sql:
    init:
      mode: always
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/online-exam-db-1
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    defer-datasource-initialization: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    enabled: true
openapi:
  service:
    title: auth-service doc
    version: 1.0.0
    url: http://localhost:8763
springdoc:
  api-docs:
    path: /api/v1/auth/v3/api-docs
  swagger-ui:
    path: /api/v1/auth/swagger-ui.html


app:
  jwt:
    secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    expiration: 1000